### PR TITLE
appended more details for the secrets error

### PR DESCRIPTION
**Pull request by BenGitsCode**
Just more detailed instructions regarding the following issues:

https://github.com/ga-wdi-boston/full-stack-project/issues/282

https://github.com/ga-wdi-boston/full-stack-project/issues/249

### CODE REVIEW

**Comment by RealWeeks** [comment]
nice @Benjamski . Thoughts on merging in @gaand? and @jrhorn424 ?

**Comment by gaand** [comment]
@J-Weeks: @Benjamski Used `git add .`.  This is almost never correct, and is not in this case.  So, no merge with that in place.

**Comment by RealWeeks** [comment]
@Benjamski want to correct and resubmit?

**Comment by BenGitsCode** [comment]
@J-Weeks my mistake. I had removed my gh repo when I saw the above comment on my use of `git add .`

I've made a new pull request correcting the issue here https://github.com/ga-wdi-boston/rails-deployment-heroku-study/pull/17

**Pull request closed without merging**
