### PR TITLE
Appended Secrets guide to avoid deployment issues

### PR DESCRIPTION
**Pull request by BenGitsCode**
-staged changes properly with better practices and NOT git. add

Just more detailed instructions regarding the following issues:

ga-wdi-boston/full-stack-project#282

ga-wdi-boston/full-stack-project#249

Thank you for catching my bad practices.

### CODE REVIEW

**Comment by gaand** [comment]
@Benjamski It still as `git add .` :-).

**Comment by BenGitsCode** [comment]
Yes, yes it did. Actually removed it this time 👍

**Comment by jrhorn424** [comment]
I'll merge this without objection @ga-wdi-boston/core.

**Comment by BenGitsCode** [comment]
Hey @jrhorn424 Merge?

**Pull request merged**
